CREATE PROCEDURE [RF]
@RFID NVARCHAR(40),
@Balance INT
AS
BEGIN
INSERT INTO [RF].[DBAPP1] (RFID) Values (@RFID);
INSERT INTO [RF].[DBAPP1] (Balance) Values (@Balance);
RETURN @@ERROR
END
GO
